### ISSUE TITLE
How can I get history data from dataloader (example/agent_motion_prediction.ipynb)

### ISSUE THREAD

**Issue by hayoung-kim** [lyft/l5kit#94]
Hello, I wonder how can I get history position and yaw of the vehicles from `dataloader`. 
In `agent_motion_prediction` example, the number of the history frames can be set at `agent_motion_config.yaml` file. 
However, when I get data from `dataloader` built from `build_dataloader` function, I cannot find history data.

Here is a code:
```
>>> tr_it = iter(train_dataloader)
>>> data = next(tr_it)

>>> print(data.keys())
dict_keys(['image', 'target_positions', 'target_yaws', 
  'target_availabilities', 'world_to_image', 'track_id', 
  'timestamp', 'centroid', 'yaw', 'extent'])
```

and here are configurations (`agent_motion_config.yaml`)
```
###################
## Model options
model_params:
  model_architecture: "resnet50"

  history_num_frames: 3
  history_step_size: 1
  history_delta_time: 0.1

  future_num_frames: 50
  future_step_size: 1
  future_delta_time: 0.1
```

How can I get history data?
Thanks!
